"""empty message

Revision ID: 520fee6175c2
Revises: 
Create Date: 2021-04-19 23:27:44.961983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520fee6175c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.Column('colour', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('transmission', sa.String(length=255), nullable=True),
    sa.Column('car_type', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('favourites',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('favourites')
    op.drop_table('cars')
    # ### end Alembic commands ###
